### PR TITLE
Fix checking object parent when the weakref is dead

### LINKED ISSUE #654: Episode reload causes "AttributeError: 'NoneType' object has no attribute '_checkAttrs'"
**Describe the issue**
This problem was introduced in #590, as the commit before it did not produce the error.  When running reload() on an episode, an "AttributeError: 'NoneType' object has no attribute '_checkAttrs'" exception is thrown in the method _isChildOf:

**Code snipppets**
image

**Expected behavior**
Running episode.reload() should not throw any exceptions.

**Enviroment (please complete the following information):**
 - OS: Windows
 - Plex version: 1.21.2.3943
 - Python Version: 3.9.1
 - PlexAPI version: 4.3.1

**Additional context**
If you're having issues reproducing, the error happens consistently in my project: https://github.com/gstacks13/plex_set_tracks.

### PR DESCRIPTION
**Pull request by JonnyWong16**
## Description

When an object is created through chaining, the `weakref` to the `episode._parent` object is dead because the season object is not saved. This fix ensures that the `weakref` is still alive when checking `_isChildOf`.

```python
>>> season = show.season(season=1)
>>> episode = season.episode(episode=1)
>>> episode._parent  # weakref is alive
<weakref at 0x0000013280F436D0; to 'Season' at 0x0000013280FC9C10>

>>> episode = show.season(season=1).episode(episode=1)
>>> episode._parent  # weakref is dead
<weakref at 0x0000013280F304A0; dead>
```

Fixes #654

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated the docstring for new or existing methods
- [x] I have added tests when applicable

### CODE REVIEW

File: plexapi/base.py [hunk 1]
```diff
@@ -119,7 +119,7 @@ def _isChildOf(self, **kwargs):
                     See all possible `**kwargs*` in :func:`~plexapi.base.PlexObject.fetchItem`.
         """
         obj = self
-        while obj._parent is not None:
+        while obj._parent is not None and obj._parent() is not None:
             obj = obj._parent()
             if obj._checkAttrs(obj._data, **kwargs):
```
Comment (Hellowlol) [inline plexapi/base.py:124]: I would prefer

```
while obj._parent is not None:
    obj = obj._parent()
    if obj is not None and obj._checkAttrs(obj._data, **kwargs):
        ...
```

Comment (JonnyWong16) [reply plexapi/base.py:124]: This will fail on the next iteration of the loop since `obj = None`.

```
AttributeError: 'NoneType' object has no attribute '_parent'
```

We could do
```python
while obj and obj._parent is not None:
    obj = obj._parent()
    if obj is not None and obj._checkAttrs(obj._data, **kwargs):
        ...
```
