### ISSUE TITLE
Episode reload causes "AttributeError: 'NoneType' object has no attribute '_checkAttrs'"

### ISSUE THREAD

**Issue by gstacks13** [pkkid/python-plexapi#654]
**Describe the issue**
This problem was introduced in #590, as the commit before it did not produce the error.  When running reload() on an episode, an "AttributeError: 'NoneType' object has no attribute '_checkAttrs'" exception is thrown in the method _isChildOf:

**Code snipppets**
![image](https://user-images.githubusercontent.com/45368106/106828352-aadd2000-664f-11eb-8598-a4081c14d885.png)

**Expected behavior**
Running episode.reload() should not throw any exceptions.

**Enviroment (please complete the following information):**
 - OS: Windows
 - Plex version: 1.21.2.3943
 - Python Version: 3.9.1
 - PlexAPI version: 4.3.1

**Additional context**
If you're having issues reproducing, the error happens consistently in my project: https://github.com/gstacks13/plex_set_tracks.

**Comment by Hellowlol** [comment]
Post the trace back. I want to see how it created.

**Comment by gstacks13** [comment]
Sure!

```
Traceback (most recent call last):
  File "C:\Users\Gabe\Projects\plex_set_tracks\plex_set_tracks.py", line 845, in <module>
    printStreams(episode)
  File "C:\Users\Gabe\Projects\plex_set_tracks\plex_set_tracks.py", line 362, in printStreams
    episode.reload()
  File "C:\Users\Gabe\Projects\plex_set_tracks\venv\lib\site-packages\plexapi-4.2.0-py3.9.egg\plexapi\base.py", line 280, in reload
  File "C:\Users\Gabe\Projects\plex_set_tracks\venv\lib\site-packages\plexapi-4.2.0-py3.9.egg\plexapi\video.py", line 741, in _loadData
  File "C:\Users\Gabe\Projects\plex_set_tracks\venv\lib\site-packages\plexapi-4.2.0-py3.9.egg\plexapi\base.py", line 222, in findItems
  File "C:\Users\Gabe\Projects\plex_set_tracks\venv\lib\site-packages\plexapi-4.2.0-py3.9.egg\plexapi\base.py", line 93, in _buildItemOrNone
  File "C:\Users\Gabe\Projects\plex_set_tracks\venv\lib\site-packages\plexapi-4.2.0-py3.9.egg\plexapi\base.py", line 78, in _buildItem
  File "C:\Users\Gabe\Projects\plex_set_tracks\venv\lib\site-packages\plexapi-4.2.0-py3.9.egg\plexapi\base.py", line 51, in __init__
  File "C:\Users\Gabe\Projects\plex_set_tracks\venv\lib\site-packages\plexapi-4.2.0-py3.9.egg\plexapi\media.py", line 65, in _loadData
  File "C:\Users\Gabe\Projects\plex_set_tracks\venv\lib\site-packages\plexapi-4.2.0-py3.9.egg\plexapi\base.py", line 222, in findItems
  File "C:\Users\Gabe\Projects\plex_set_tracks\venv\lib\site-packages\plexapi-4.2.0-py3.9.egg\plexapi\base.py", line 93, in _buildItemOrNone
  File "C:\Users\Gabe\Projects\plex_set_tracks\venv\lib\site-packages\plexapi-4.2.0-py3.9.egg\plexapi\base.py", line 78, in _buildItem
  File "C:\Users\Gabe\Projects\plex_set_tracks\venv\lib\site-packages\plexapi-4.2.0-py3.9.egg\plexapi\base.py", line 51, in __init__
  File "C:\Users\Gabe\Projects\plex_set_tracks\venv\lib\site-packages\plexapi-4.2.0-py3.9.egg\plexapi\media.py", line 148, in _loadData
  File "C:\Users\Gabe\Projects\plex_set_tracks\venv\lib\site-packages\plexapi-4.2.0-py3.9.egg\plexapi\media.py", line 156, in _buildStreams
  File "C:\Users\Gabe\Projects\plex_set_tracks\venv\lib\site-packages\plexapi-4.2.0-py3.9.egg\plexapi\base.py", line 222, in findItems
  File "C:\Users\Gabe\Projects\plex_set_tracks\venv\lib\site-packages\plexapi-4.2.0-py3.9.egg\plexapi\base.py", line 93, in _buildItemOrNone
  File "C:\Users\Gabe\Projects\plex_set_tracks\venv\lib\site-packages\plexapi-4.2.0-py3.9.egg\plexapi\base.py", line 78, in _buildItem
  File "C:\Users\Gabe\Projects\plex_set_tracks\venv\lib\site-packages\plexapi-4.2.0-py3.9.egg\plexapi\base.py", line 51, in __init__
  File "C:\Users\Gabe\Projects\plex_set_tracks\venv\lib\site-packages\plexapi-4.2.0-py3.9.egg\plexapi\media.py", line 373, in _loadData
  File "C:\Users\Gabe\Projects\plex_set_tracks\venv\lib\site-packages\plexapi-4.2.0-py3.9.egg\plexapi\base.py", line 124, in _isChildOf
AttributeError: 'NoneType' object has no attribute '_checkAttrs'
```
